# <font color="darkblue"> Praticando Regressão Logística - Ataque de Coração</font>

**Objetivos:**


*   Apresentar  plataforma Kaglee
*   Inferir dados de uma base real utilizando o algoritmo de Regressão Logística

**Requisitos de execução:**


*   Upload do arquivo *heart_failure_clinical_records_dataset.csv*

**Atividade 1:**

1. Visitar a base de dados: https://www.kaggle.com/andrewmvd/heart-failure-clinical-data
2. Carregar os dados do arquivo *heart_failure_clinical_records_dataset.csv* utilizando o pandas.

    

In [ ]:
import pandas as pd
import numpy as np

heart_data = pd.read_csv('heart_failure_clinical_records_dataset.csv')
print(heart_data.head())


    age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2       

**Atividade 2:**

1. Extrair os valores do *DataFrame* pandas e colocar nas variáveis


In [ ]:
from sklearn.preprocessing import StandardScaler
#fazer predictivas pelo rótulo com correlação

Features = ['time','anaemia','creatinine_phosphokinase','diabetes','ejection_fraction','serum_creatinine','age', 'high_blood_pressure', 'platelets', 'serum_sodium', 'sex', 'smoking']

# sc = StandardScaler()
# sc.fit(heart_data[Features].values)

X = heart_data[Features].values
y = heart_data["DEATH_EVENT"].values

print("d: " + str(len(Features)))
print("N: " + str(len(y)))
print(X)

d: 12
N: 299
[[4.000e+00 0.000e+00 5.820e+02 ... 1.300e+02 1.000e+00 0.000e+00]
 [6.000e+00 0.000e+00 7.861e+03 ... 1.360e+02 1.000e+00 0.000e+00]
 [7.000e+00 0.000e+00 1.460e+02 ... 1.290e+02 1.000e+00 1.000e+00]
 ...
 [2.780e+02 0.000e+00 2.060e+03 ... 1.380e+02 0.000e+00 0.000e+00]
 [2.800e+02 0.000e+00 2.413e+03 ... 1.400e+02 1.000e+00 1.000e+00]
 [2.850e+02 0.000e+00 1.960e+02 ... 1.360e+02 1.000e+00 1.000e+00]]


**Atividade 3:**

1. Separar os dados em conjunto de treinamento e teste


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Validação cruzada
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=10)

sc1 = StandardScaler()
sc1.fit(X_train)
X_train = sc1.transform(X_train)
X_test = sc1.transform(X_test)

print("Tamanho treinamento: " + str(len(X_train)))
print("Tamanho teste: " + str(len(X_test)))

print(X_train)

Tamanho treinamento: 224
Tamanho teste: 75
[[-0.25630788 -0.85815739 -0.12725554 ... -1.06908268 -1.34164079
  -0.64631379]
 [-0.14127745 -0.85815739 -0.47592317 ... -0.62520035  0.74535599
   1.54723605]
 [-0.49914989  1.16528741 -0.44932183 ...  0.04062316 -1.34164079
  -0.64631379]
 ...
 [-1.48329911  1.16528741 -0.22511049 ... -0.18131801  0.74535599
  -0.64631379]
 [-0.40968178  1.16528741 -0.2450615  ... -0.40325918 -1.34164079
  -0.64631379]
 [ 1.4180239   1.16528741 -0.30206438 ...  0.70644667  0.74535599
   1.54723605]]


**Atividade 4:**
1. Inferir a função a função hipótese $g(x)=\theta(w^Tx)$ dos dados de treinamento com a classe LogisticRegression do pacote *sklearn.metrics*
2. Computar as métricas de aprendizado sobre o dados de teste.
3. Aplique a normalização dos dados de entrada e reexecute todos os experimentos. Compare os resultados.

In [ ]:
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

print(classification_report(y_test, model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.88      0.84      0.86        55
           1       0.61      0.70      0.65        20

    accuracy                           0.80        75
   macro avg       0.75      0.77      0.76        75
weighted avg       0.81      0.80      0.80        75



**Atividade 5:**

1. Exiba os parâmetros (Features) de $X$ ordenados pela sua importância na função de decisão, este valor é indicado pelo vetor $w$. No pacote sklearn.linear_model.LogisticRegression, utilize o atributo $coef_$.

In [ ]:
param = [(np.exp(coef), f) for coef, f in zip(model.coef_[0], Features)]
param.sort(reverse=True)

for p in param:
  print(p)

(2.921257765573557, 'serum_creatinine')
(1.8620500504662179, 'age')
(1.205887120110878, 'creatinine_phosphokinase')
(1.1695120543068467, 'diabetes')
(1.126585143927085, 'anaemia')
(0.944308592551142, 'smoking')
(0.9123610391646991, 'high_blood_pressure')
(0.8882293061569555, 'platelets')
(0.8437286106209704, 'sex')
(0.7766524152537242, 'serum_sodium')
(0.3735863677818731, 'ejection_fraction')
(0.20403312374675692, 'time')
